### ISSUE TITLE
Падает opm в 15-м односкрипте (из-за ДиспетчерКомандПриложения)

### ISSUE THREAD

**Issue by dmpas** [oscript-library/opm#1]
```
{Модуль /usr/share/oscript/lib/opm/src/opm.os / Ошибка в строке: 51 / Внешнее исключение (System.Collections.Generic.KeyNotFoundException): The given key was not present in the dictionary.}
```

https://github.com/oscript-library/opm/blob/master/src/opm.os#L51

14-й Односкрипт не ругается на эту строчку, но мне кажется, это ошибка в ОПМ, потому как объекта такого я не нашёл. Видимо, 15-й правильно ругается.

**Comment by EvilBeaver** [comment]
Полагаю, что это все-таки ошибка движка, ее раньше не было. Я колупался с контекстами вчера, исправляя https://github.com/EvilBeaver/OneScript/issues/330, возможно, сломал.

**Comment by dmpas** [comment]
но ведь такого класса и правда нет. То есть синтаксический контроль должен падать. Разве нет?

**Comment by artbear** [comment]
@dmpas Такой класс есть [src/Классы/ДиспетчерКомандПриложения.os](https://github.com/oscript-library/opm/blob/master/src/%D0%9A%D0%BB%D0%B0%D1%81%D1%81%D1%8B/%D0%94%D0%B8%D1%81%D0%BF%D0%B5%D1%82%D1%87%D0%B5%D1%80%D0%9A%D0%BE%D0%BC%D0%B0%D0%BD%D0%B4%D0%9F%D1%80%D0%B8%D0%BB%D0%BE%D0%B6%D0%B5%D0%BD%D0%B8%D1%8F.os)

**Comment by dmpas** [comment]
@artbear эх, я! виноват, неправильно грепал. Значит, ошибка движка всё-таки.

**Comment by artbear** [comment]
@dmpas переоткроешь баг в репо 1скрипта? чтобы не забылось.

**Comment by dmpas** [comment]
@artbear ага, готовлю воспроизводимое описание.
