### ISSUE TITLE
Ошибка при выполнении команды "opm update -all" после перехода на 20 релиз

### ISSUE THREAD

**Issue by nikolainp** [oscript-library/opm#109]
После обновления с 18 релиза на 20 появилась ошибка:

C:\Windows\system32>opm update -all
КРИТИЧНАЯОШИБКА - {Модуль C:\Program Files (x86)\OneScript\lib\opm\src\Классы\Ре
по.os / Ошибка в строке: 123 / Свойство  недоступно для записи}

**Comment by dmpas** [comment]
если попробовать сделать сначала `opm update opm` ?

**Comment by nikolainp** [comment]
честно говоря, я успел обойти эту проблему.
сейчас ошибка не повторяется, в новой установке так же такой ошибки нет.
у меня сложилось впечатление, что ошибка связана с тем, что, возможно, есть системная переменная "НастройкиПриложения", которая закрыта для записи.
потому что падало на строчке:
НастройкиПриложения = НастройкиПриложенияOpm.Получить();
