### ISSUE TITLE
Выпуск 0.14.0

### ISSUE THREAD

**Issue by nixel2007** [oscript-library/opm#110]
Для нового гитсинка от @khorevaa

**Comment by khorevaa** [comment]
@nixel2007 не спеши с релизом. Видимо еще надо будет допилить чутка

**Comment by nixel2007** [comment]
как будет надо - пингуй

**Comment by khorevaa** [comment]
Теперь надо! Я готов к выпуске беты )

**Comment by asosnoviy** [comment]
Все же вышло?
