### ISSUE TITLE
Прописывать файл запуска в каталог из переменной OSCRIPTBIN

### ISSUE THREAD

**Issue by khorevaa** [oscript-library/opm#114]
Сейчас строго прописывается в /usr/bin
В работе с ovm - это не подходит т.к. надо писать в каталог где работает ovm

**Comment by khorevaa** [comment]
Уже сделано!

**Comment by nixel2007** [comment]
Это сделано только при первичной установке движка через ovm. Обновление опм перезатрет батник :/
