### ISSUE TITLE
Очистка каталога пакета при установке/обновлении пакета

### ISSUE THREAD

**Issue by artbear** [oscript-library/opm#116]
Обе команды, install и update, чистят только os-файлы. 
Остальные файлы сейчас пакет должен чистить за собой сам.

Предложение - сделать автоочистку каталога пакета при установке/обновлении пакета

@nixel2007 @khorevaa

**Comment by nixel2007** [comment]
Много пакетов зависят от конфиг файлов в каталоге пакета. Тот же опм тоже. Так что огульно это делать нельзя

**Comment by asosnoviy** [comment]
Директивы в packgedef какие то?  
 ("УдалятьПриобновлении", "*.os")
 ("УдалятьПриобновлении", "*")
 ("УдалятьПриобновлении", ".epf, .os")

**Comment by EvilBeaver** [comment]
В конфиг файле есть обработчики событий ПередУстановкой и ПриУдалении

**Comment by asosnoviy** [comment]
@EvilBeaver а ткни носом, полез копать и не нашел =(

**Comment by EvilBeaver** [comment]
https://github.com/oscript-library/opm/blob/master/src/core/%D0%9A%D0%BB%D0%B0%D1%81%D1%81%D1%8B/%D0%A3%D1%81%D1%82%D0%B0%D0%BD%D0%BE%D0%B2%D0%BA%D0%B0%D0%9F%D0%B0%D0%BA%D0%B5%D1%82%D0%B0.os#L189

**Comment by EvilBeaver** [comment]
И вот тут еще https://github.com/oscript-library/opm/blob/master/src/core/%D0%9A%D0%BB%D0%B0%D1%81%D1%81%D1%8B/%D0%A1%D0%B1%D0%BE%D1%80%D1%89%D0%B8%D0%BA%D0%9F%D0%B0%D0%BA%D0%B5%D1%82%D0%B0.os#L262

**Comment by artbear** [comment]
В Add есть примеры использования 2 или 3 событий из 4

пт, 6 июл. 2018 г., 19:16 Andrei Ovsiankin <notifications@github.com>:

**Comment by artbear** [comment]
Реализовано событие ПередУстановкой.
Используется в Vanessa.ADD https://github.com/silverbulleters/add/issues/291
