### ISSUE TITLE
Не работает установка пакетов содержащих верхний регистр

### ISSUE THREAD

**Issue by khorevaa** [oscript-library/opm#119]
Версия 0.14.1
`opm install ParserFileV8i`
Ошибка
```
КРИТИЧНАЯОШИБКА - {Модуль /Users/khorevaa/.local/share/ovm/current/lib/opm/src/core/Классы/МенеджерПолученияПакетов.os / Ошибка в строке: 18 / Ошибка установки пакета ParserFileV8i: Пакет не найден}
```

**Comment by EvilBeaver** [comment]
Обновить opm, по-моему надо

**Comment by EvilBeaver** [comment]
или что-то еще обновить. Старая ошибка

**Comment by asosnoviy** [comment]
Это еще раз вылезло.

**Comment by khorevaa** [comment]
@EvilBeaver Я накосячил ) Можно так сказать при большом рефакторинге

**Comment by allustin** [comment]
@khorevaa исправленная версия пока не выложена ;-) - пока всем приезжает плохая ;-)

http://hub.oscript.io/download/opm/

**Comment by asosnoviy** [comment]
@allustin если есть право на пушь, выложи плз.

**Comment by allustin** [comment]
@asosnoviy наверное есть - но я ни разу не делал, поэтому боюсь ;-), чего делать то надо

**Comment by asosnoviy** [comment]
Зарелизить 0.14.2 пропатченный.  
Сбрать пакет opm build .
Забросить пакет в хаб opm push

**Comment by allustin** [comment]
@asosnoviy нет - это не ко мне, я же плохой - мне такое не дали

**Comment by asosnoviy** [comment]
@artbear Тогда к тебе...

**Comment by EvilBeaver** [comment]
Блин, чо происходит, а? Что куда выложить нужно, кому что не дали?

**Comment by EvilBeaver** [comment]
```
The oscript-library organization has their default repository permission set to write. This means that every member of this organization has write access to this repository, regardless of the team and collaborator access specified below.
```

Пушить в opm-hub могут все, кто имеет право записи в репо. @allustin входит в организацию oscript-library, с дефолтным правом записи.
