### ISSUE TITLE
Обновить все установленные библиотеки - opm update -all

### ISSUE THREAD

**Issue by sergpogo** [oscript-library/opm#12]
Такой командой (или подобной) хочется обновлять существующие локально пакеты.

`opm update -all` - Обновить все установленные библиотеки из всех каталогов библиотек, указанных в `oscript.cfg`

**Comment by artbear** [comment]
opm update -all - Обновить все установленные библиотеки из всех каталогов библиотек, указанных в oscript.cfg

**Comment by EvilBeaver** [comment]
Баба яга против. Огульные апдейты могут сломать что-то и неизвестно где искать

**Comment by artbear** [comment]
@EvilBeaver это нормальный функционал.
я как пользователь (не разработчик) хотел бы получить последние версии без излишних сложностей.
Ответственность по выкладке в хаб несет разработчик, а вот ответственность за обновления у меня.

**Comment by nixel2007** [comment]
@EvilBeaver за выполнение такого скрипта где-то на продакте я бы сам по рукам надавал раскаленной кочергой (ты наверное помнишь мои извраты с oscript-library сабмодулем).

Но в "обычной" жизни - штука полезная и я тоже думал о такой функциональности

**Comment by EvilBeaver** [comment]
Ок, я не против

**Comment by asosnoviy** [comment]
У меня есть реализация, но она зависима от функционала remote -list, PR сделаю после того как утрясем формат списка пакетов в хабе.

**Comment by JohnyDeath** [comment]
list уже есть (кстати, а почему -remote, а не --remote?)

А можно еще до кучи попросить opm install -all ?

**Comment by nixel2007** [comment]
> list уже есть (кстати, а почему -remote, а не --remote?)

согласен, косяк.

**Comment by JohnyDeath** [comment]
> оно точно тебе нужно?)

Хотелось бы сразу иметь все пакеты у себя локально, и уже на своей машине с ними разбираться.
Я вообще за то, чтобы эти 20 пакетов поставлялись сразу вместе с платформой. Многие люди вообще не знают, что уже создана достаточно большая база и начинают изобретать свои велосипеды.

Поэтому я отвечу да, мне это нужно )
