### ISSUE TITLE
Переписать приложение на CLI

### ISSUE THREAD

**Issue by khorevaa** [oscript-library/opm#126]
@nixel2007 @EvilBeaver @artbear 

Кто против если я это сделаю? )

**Comment by nixel2007** [comment]
я только за. люблю сдш

**Comment by EvilBeaver** [comment]
Никто не против, если оно сможет ставить пакеты и сохранит синтаксис основных команд.

**Comment by EvilBeaver** [comment]
Но раз пошла такая пьянка, то полагаю, можно убрать глобальную установку по умолчанию и к флагу install -l добавить флаг install -g

**Comment by EvilBeaver** [comment]
В этом месте @nixel2007 ликует

**Comment by nixel2007** [comment]
ияохерелпросто.ави

**Comment by khorevaa** [comment]
@EvilBeaver Синтаксис команд сохранит, а вот часть флагов c `-` будет с `--`. И будет последовательность сначала опции - потом аргументы.

Ну что делаем? )

**Comment by EvilBeaver** [comment]
да

**Comment by EvilBeaver** [comment]
само

**Comment by khorevaa** [comment]
Сделано #127
