### ISSUE TITLE
Показать все установленные библиотеки - opm list

### ISSUE THREAD

**Issue by artbear** [oscript-library/opm#13]
`opm list` - Показать все установленные библиотеки из всех каталогов библиотек, указанных в `oscript.cfg`

**Comment by nixel2007** [comment]
Добавлю - `opm list -remote` - показывает список пакетов в хабе

**Comment by sergpogo** [comment]
Добавлю `opm list -diff` - показывает некий check того что есть/нет, обновлено/не обновлено

**Comment by asosnoviy** [comment]
По opm list -remote 
Для железной работы надо чтобы где-то лежал этот список...
Сейчас есть предложение разбирать HTML [Отсюда](http://hub.oscript.io/download/)   
Плюс:
- Просто  и быстро

Минус:
-  При изменении верстки может ломаться.

**Comment by artbear** [comment]
У нас сейчас настроено автообновление хаба (репо https://github.com/oscript-library/library-support )
ИМХО вполне возможно выкладывать спец.список установленных пакетов в отдельный файл хаба.
И именно его анализировать.

Конечно, может быть проблема с дублирование и неактуальностью файла.
Но при автоматическом обновлении указанным инструментов ИМХО проблем не должно быть, естественно, когда инструмент научится готовить подобный файл.

@nixel2007 @EvilBeaver что скажете?

**Comment by nixel2007** [comment]
@artbear автообновление хаба пока **не** настроено.
Отдельный список формировать можно, да.
