### ISSUE TITLE
Как установить пакет в произвольное место?

### ISSUE THREAD

**Issue by artbear** [oscript-library/opm#130]
Начало обсуждения в https://gitter.im/EvilBeaver/oscript-library?at=5b619508c83d1230b13f3528

@khorevaa @nixel2007 @EvilBeaver Мужчины, а сейчас никак нельзя поставить пакет в произвольное место через `opm install` ?

Раньше я в тестах писал `opm install -f ФайлПакета.ospx -l` и мне приезжал пакет со всеми зависимостями в каталог oscript_modules.

в результате я мог спокойно тестить дев-версию пакета, не нарушая работу основных пакетов.

сейчас, в последних opm, в каталог `oscript_modules` приезжают только влияющие пакеты, а сам пакет ставится в каталог движка :(

@khorevaa @nixel2007 @EvilBeaver вопрос - как поставить пакет в произвольное место через opm install для целей разработки/тестирования??

Написать `opm install -f ФайлПакета.ospx -l -dest` нельзя, т.к. выдается предупреждение
`ПРЕДУПРЕЖДЕНИЕ - При локальной установке параметр -dest игнорируется`

**Comment by khorevaa** [comment]
В принципе исправить не сложно 
https://github.com/oscript-library/opm/blob/develop/src/core/%D0%9A%D0%BB%D0%B0%D1%81%D1%81%D1%8B/%D0%9C%D0%B5%D0%BD%D0%B5%D0%B4%D0%B6%D0%B5%D1%80%D0%A3%D1%81%D1%82%D0%B0%D0%BD%D0%BE%D0%B2%D0%BA%D0%B8%D0%9F%D0%B0%D0%BA%D0%B5%D1%82%D0%BE%D0%B2.os#L52

Вот тут надо добавить переопределение целевого каталога установки и остальное по мелочи

**Comment by artbear** [comment]
@khorevaa Да, похоже.

И какую команду нужно будет запустить, чтобы установить продукт локально?
приведи пример для большего понимания
`opm install vanessa-runner ???`

**Comment by artbear** [comment]
@khorevaa а теперь как отличить штатную установку (в каталог движка) от установки в текущий каталог?

**Comment by khorevaa** [comment]
@artbear Не понял вопроса... Что такое штатная установка и установка в текущий каталог? 
Разве они не флагом `-l` отличаются

**Comment by artbear** [comment]
>Что такое штатная установка и установка в текущий каталог?
- штатная установка ставит пакет в каталог lib движка
- установка в текущий каталог ставит пакет в текущем каталога, а не каталоге lib движка

@khorevaa хорошо, расскажи, что делают 2 команды или должны делать
1 `opm install МойПакет`
2 `opm install -l МойПакет`
и в чем между ними разница ?

**Comment by nixel2007** [comment]
1 ставит в `lib.system`, 2 ставит в `./oscript_modules`

**Comment by artbear** [comment]
Да, именно такое поведение раньше и было, а сейчас оно сломано, о чем, собственно, этот ишуз  :)

**Comment by EvilBeaver** [comment]
Оно не сломано, а изменено. Но, вероятно неправильно. Обсуждалось вот здесь https://github.com/oscript-library/opm/issues/126#issuecomment-405663346

**Comment by artbear** [comment]
я вижу, что флага `-g` не появилось, но его умолчальное действие включилось :)

мне нравится идея с этим флагом, если его ввести, то проблема установки из этого ишуза решается легко и просто.

**Comment by khorevaa** [comment]
> 1 ставит в lib.system, 2 ставит в ./oscript_modules

Вот так и будет работать. Уже сделал осталось тест написать на эту тему...

**Comment by artbear** [comment]
@khorevaa в ванесса-раннер есть фича opm-build, которая проверяет сборку пакета и его установку как раз через `install -l`
можешь там посмотреть.

**Comment by khorevaa** [comment]
Выполнено #131
