### ISSUE TITLE
opm update без ключа - нечитабельная ошибка

### ISSUE THREAD

**Issue by allustin** [oscript-library/opm#133]
если вызвать 

```
opm update
```

будет выдано что `пакет не найден` да еще и синтаксической ошибкой

![image001](https://user-images.githubusercontent.com/55323/43850681-3c6a66f4-9b41-11e8-9ecd-6a31b6fd1ecc.png)

**Comment by artbear** [comment]
В 0.15.0 этой проблемы нет, там cli
