### ISSUE TITLE
Новое событие ПередУстановкой внутри packagedef

### ISSUE THREAD

**Issue by artbear** [oscript-library/opm#134]
Существующих событий перестало хватать
Опишу свой кейс:
пакет vanessa.add, все о нем знают.
этот пакет внутри себя имеет набор каталогов разной вложенности с набором epf-файлов (внешних обработок)
и выясняется проблема - при обновлении новой версии add поверх существующей, старой версиии через opm из архива поставки происходит установка всех файлов из пакета.

Но старые файлы не удаляются :(
в итоге файлы двух версий смешиваются и получается баг обновления.
Вот ишуз https://github.com/silverbulleters/add/issues/291

Существующего события ПриУстановке для решения проблемы недостаточно, т.к. оно срабатывает уже **после** извлечения всех файлов из поставки и установки их в каталог установки, т.е. когда все файлы перемешались.

и в этом событии нет доступа к архиву пакета, так что даже сверить файлы с источником нельзя :(
 
Предлагаю:

- [x]  добавить новое событие `ПередУстановкой(Знач КаталогУстановкиПакета, Знач АрхивПакета, СтандартнаяОбработка) Экспорт`
которое поможет выполнять действие перед установкой

- [ ] Также дополнительно будет полезен спец.метод `Описание.ОчиститьПередУстановкой(МаскаФайлов, ВключитьПодкаталоги)`
для простого решения указанной задачи без написания доп.обработки

@khorevaa @EvilBeaver @nixel2007 Могу сделать, если нет возражений.

**Comment by artbear** [comment]
Выполнено

**Comment by artbear** [comment]
@khorevaa @EvilBeaver @nixel2007 Выпустим релиз 1.0.0 с переводом opm на cli и моими последними правками.
давно пора версию 1.0.0 выпускать
+ add ждет события ПередУстановкой в https://github.com/silverbulleters/add/issues/291

**Comment by nixel2007** [comment]
Я уже говорил, что я хотел бы видеть в 1.0.0 - версию манифеста. Уж если на
джсон переходить страшно (отложим до 2.0 вероятно).

чт, 30 авг. 2018, 23:16 Artur Ayukhanov <notifications@github.com>:

**Comment by khorevaa** [comment]
@artbear ДУмаю можно выпустить! Хотя я бы сменить формат packagedef перед версией 1.0.0 иначе потом совместимость и прочие! А тут cli и так  фактически вводит другую строку вызова

**Comment by EvilBeaver** [comment]
Ох, доберусь я до вас!

*В смысле, никак не доберусь подключиться к opm, хотя и ключевой продукт*

**Comment by artbear** [comment]
@khorevaa @EvilBeaver @nixel2007 Релиз будем выпускать??
0.15 ??
событие ПередУстановкой очень нужно.

**Comment by khorevaa** [comment]
@artbear Я не против!
