### ISSUE TITLE
Флаг установки при сборке

### ISSUE THREAD

**Issue by khorevaa** [oscript-library/opm#136]
Предлагаю добавить возможность установки собранного пакета после команды build
Уменьшиться лишний вызов и появится возможность тестировать ПО сразу после установки

**Comment by artbear** [comment]
@khorevaa ты описал кейс разработчика, а предлагаешь добавить ключик, доступный для пользователя.
Это не хорошо.

Если нет пользовательского сценария под ключ, тогда лучше и не добавлять.

**Comment by nixel2007** [comment]
Если честно мне не очень нравится эта идея. У install уже слишком много флагов, чтобы переносить их в build. В крайнем случае наоборот в install добавить --build с путем к каталогу сборки вместо файла.

**Comment by khorevaa** [comment]
@nixel2007 В принципе можно и в инсталл флаг билд!

**Comment by EvilBeaver** [comment]
я в целом против. Оболочки умеют && этого достаточно, имхо
