### ISSUE TITLE
Не работает событие ПередУстановкой

### ISSUE THREAD

**Issue by artbear** [oscript-library/opm#138]
В продолжение https://github.com/oscript-library/opm/issues/134

После установки 0.15.0 событие все равно не обрабатывается :(

**Comment by artbear** [comment]
Да и событие ПриУстановке также не отрабывает :(

т.е. в 0.14 опять поломали :(

добавлю тест на это дело.

**Comment by EvilBeaver** [comment]
@artbear кто что поломал в 0.14, поясни, пожалуйста. Какая строка кода была сломана?

**Comment by artbear** [comment]
удалить packagedef был все-таки ошибочным.
т.е. мы
+ удаляем старый packagedef
+ ищем обработчик событий ПриУстановке (ПередУстановкой) в новом packagedef, которого тупо нет
+ и только потом извлекаем все файлы из архива, в т.ч. и новый packagedef

я лишь изменил порядок выполнения на правильный
+ удаляем старый packagedef
+ извлекаем новый packagedef
+ ищем обработчик событий ПриУстановке (ПередУстановкой) в новом packagedef, которого тупо нет
+ вызываем событие ПередУстановкой
+ и только потом извлекаем все файлы из архива, в т.ч. и новый packagedef
+ вызываем событие ПриУстановке

ну и все на тестах/фичах, как обычно, в https://github.com/oscript-library/opm/pull/139

**Comment by artbear** [comment]
Выполнено
