### ISSUE TITLE
opm не работает под linux

### ISSUE THREAD

**Issue by nixel2007** [oscript-library/opm#142]
{Модуль /usr/share/oscript/lib/opm/src/cmd/opm.os / Ошибка в строке: 17 / Библиотека не найдена "../core"}

**Comment by nixel2007** [comment]
![image](https://user-images.githubusercontent.com/1132840/46584229-59193080-ca69-11e8-8044-a170846980fe.png)

**Comment by khorevaa** [comment]
@EvilBeaver Я думаю это новый Zip виноват!

**Comment by artbear** [comment]
Закрываю как уже исправленную.

проверил на линукс релиз 1скрипт 1.1.1, проблем нет.
