### ISSUE TITLE
Возможность использования собственных репозитариев пакетов

### ISSUE THREAD

**Issue by Dumsik** [oscript-library/opm#143]
Хотелось бы иметь возможность сохранять в настройках opm путь к собственным репозитариям пакетов и соответственно устанавливать пакеты из них.
Данная возможность очень востребована на  предприятиях т.к. создается большое число пакетов которые нужны только на этом конкретном предприятии и публиковать их в публичном хабе смысла нет. 
Сейчас очень не удобно получается, админ или программист при установке пакета должен указывать путь к пакету для его установки, а обновление через opm update [имя пакета] вообще не возможно. А так можно было бы просто вызвать opm с именем пакета и он бы установился из этого репо. Соответственно обновление то же работало бы автоматически. Для пакетов которые должны искаться в локальных репо можно ввести обязательный префикс например local_[имя пакета] и тогда opm понимал бы что нужно искать/обновлять пакет в локальном репозитарии.

**Comment by nixel2007** [comment]
Это уже есть. в настройках opm есть понятие "зеркала".

**Comment by Dumsik** [comment]
через opm --h не вижу. Как посмотреть описание?

**Comment by nixel2007** [comment]
Попробуйте хелп по команде config

**Comment by Dumsik** [comment]
Хелп по команде config ничего не показывает. Посмотрел в коде, действительно есть. Попробую доработать и сделать PR чтобы хелп выводил информацию о настройках своих зеркал.

**Comment by nixel2007** [comment]
Спасибо! Доработки хелпа будут очень в тему, мне казалось, что там это есть (ну или хотя бы в ридми)
