### ISSUE TITLE
Всегда используется прокси по умолчанию

### ISSUE THREAD

**Issue by L0z4** [oscript-library/opm#145]
https://github.com/oscript-library/opm/blob/9e43b88cbc0c92ebd247e085cfd9c93d04f1f537/src/core/%D0%9C%D0%BE%D0%B4%D1%83%D0%BB%D0%B8/%D0%9D%D0%B0%D1%81%D1%82%D1%80%D0%BE%D0%B9%D0%BA%D0%B8Opm.os#L76

из-за этой строки, независимо от введенных настроек прокси, прокси не используется. Если ее убрать - работает согласно введенным настройкам.
Возможно есть смысл обрамить в виде
```
Если ЗначениеНастройки Тогда
 мНастройки.ИспользоватьПрокси = ЛОЖЬ;
КонецЕсли;
```

**Comment by khorevaa** [comment]
@L0z4 Дайте файл настройки opm.cfg 
Вы точно устанавливали `-proxyusedefault`?

**Comment by L0z4** [comment]
```
{
    "СоздаватьShСкриптЗапуска": false,
    "Прокси": {
        "Сервер": "proxy.asdf.ru",
        "Порт": "3128",
        "Пользователь": "1c_server",
        "Пароль": "blablabla",
        "ИспользоватьАутентификациюОС": false,
        "ИспользоватьПрокси": true,
        "ПроксиПоУмолчанию": false
    },
    "СервераПакетов": []
}
```
цель - именно использовать настройки прокси из этого конфига, а не default. Но если "ПроксиПоУмолчанию": false то все остальные значения конфига игнорировались.

**Comment by khorevaa** [comment]
`ПроксиПоУмолчанию` отвечает за использование именно системного прокси.
`ИспользоватьПрокси` - отвечает именно вообще за использование ЛЮБОГО прокси

Может у Вас тут путаница?

**Comment by EvilBeaver** [comment]
Это у нас непонятный конфиг, вызывающий путаницу. Флаг использования прокси нужен всегда, как для системного, так и не для системного. Если вообще никакого прокси нет, то флаг этот должен быть Ложь. А если хоть какой-то есть - должен быть Истина.

А если этот флаг установлен в Истина, но подтягивает только default system proxy, а не заданные параметры - то это вроде как баг.

Надо по коду смотреть.

**Comment by bia-tech** [comment]
Поправил #146
