### ISSUE TITLE
Зачем и когда поменяли параметры команды build

### ISSUE THREAD

**Issue by artbear** [oscript-library/opm#147]
В старых версиях работала команда `opm build . -out resDir`

А сейчас не так
```
W:\repo\SB>opm build --help
Команда: b, build
 Собрать пакет из исходников

Строка запуска: opm b [ОПЦИИ] [SRC]

Аргументы:
  SRC           Каталог исходников

Опции:
  -m, --mf, --manifest-file     Файл манифеста сборки (packagedef)
  -o, --out, --out-dir          Выходной каталог
```

Из нового описания видно, что опция --out теперь должна быть ДО каталога исходников.

Из-за этого падают ранее написанные тесты и фичи в разных пакетах - ванесса-раннер, add, 1бдд и т.п.. которые тестировали сборку своих пакетов

@nixel2007 @khorevaa @EvilBeaver Предлагаю вернуть старое поведение для совместимости.

или предоставить хорошие аргументы для нового поведения :)

**Comment by nixel2007** [comment]
Старое поведение некорректно с точки зрения стандартов posix, разницы в аргументах и опциях и библиотеки cli.

Я сохранение нового поведения, более соответствующего нормам разработки консольных приложений.

**Comment by khorevaa** [comment]
@artbear Изменения внес я когда переводил на `cli`

Тут есть два изменения
1. Сделан строгий порядок сначала опции, а потом аргументы - это можно вернуть, но это приведет к тому что аргумент `SRC` - станет обязательный и не будет по умолчанию использовать текущий каталог. 
2. Согласно стандарту POSIX - короткие опции должны иметь `-` и не более одного символа, а длинные `--` и любое количество символов, в связи с этим старый флаг `-mf` и `-out` становятся не работоспособными т.к. имеют  у себя длину 2 символа и должны проходить как длинные опции и перед ними должно стоять `--`. Что приводит к необходимости их переопределения в уже существующих местах.

В связи с тем, что пункт 2 не выполним в `cli`, при переводе на `cli`, я решил и не сохранять совместимость со строкой использования в рамках пункта 2. Это же касается и других команд, если там использовались длинные опции с `-` вместо `--`

**Comment by khorevaa** [comment]
@artbear @nixel2007 Вот где я на косячил - так эти несовместимости не описаны в описании релиза! Надо исправить!

**Comment by nixel2007** [comment]
v0.x в конце-то концов. :) @Khorevaa можешь прислать пр в ридми, типа "переход на версию... 14?" а я скопипасчу потом в релиз ноты

**Comment by dmpas** [comment]
> v0.x в конце-то концов

моя душить за такой дело!!!

**Comment by nixel2007** [comment]
Моя душенька успокоится с 1.0 после добавления в манифест метода "ВерсияМанифеста", кидающей исключение, если что не так.

**Comment by artbear** [comment]
@khorevaa Аргументы принимаются.
Да, главная проблема в доке на изменения.
Жду пр, как предложил Никита

**Comment by khorevaa** [comment]
Справка добавлена
