### ISSUE TITLE
ВызватьИсключение и не рушит управляющий скрипт

### ISSUE THREAD

**Issue by nixel2007** [oscript-library/opm#15]
Сабж. В случае `opm test` это немного бяда.

https://github.com/nixel2007/gitrunner/pull/5/files#diff-e8ca789ed3f2f3f0121f4e7e117df3f9

**Comment by nixel2007** [comment]
Вообще этот скрипт загружается через ЗагрузитьСценарий. Выглядит как баг в движке oscript
/cc @EvilBeaver @dmpas

**Comment by EvilBeaver** [comment]
Можешь пояснить?

**Comment by nixel2007** [comment]
@EvilBeaver если в теле модуля скрипта, загружаемого через ЗагрузитьСценарий() вызвать исключение, то сценарий-родитель не упадет, а продолжит свою работу
https://github.com/oscript-library/opm/blob/master/src/%D0%9A%D0%BB%D0%B0%D1%81%D1%81%D1%8B/%D0%98%D1%81%D0%BF%D0%BE%D0%BB%D0%BD%D0%B8%D1%82%D0%B5%D0%BB%D1%8C%D0%97%D0%B0%D0%B4%D0%B0%D1%87.os#L40

**Comment by EvilBeaver** [comment]
Забавно. Раньше вроде как падало. ЗавершитьРаботу сразу убивает все. Это не исключение, это TerminateProcess. А вот обычная ошибка должна выброситься наверх, конечно

**Comment by nixel2007** [comment]
@EvilBeaver мне ждать фикса движка, правильно понимаю?

**Comment by EvilBeaver** [comment]
Ну анализа почему так - точно ждать

**Comment by artbear** [comment]
@nixel2007 @EvilBeaver Добавлен [PR 372](https://github.com/EvilBeaver/OneScript/pull/372) для демонстрации бага выброса исключения при загрузке сценарий
Тест проходит!!
У меня свежая ночная сборка.

В итоге проблема в чем-то другом.
Возможно, что проблема именно в классе, подключенном через библиотеки.

**Comment by artbear** [comment]
Добавлен еще один тест вызова исключения из метода библиотечного объекта.
Падения опять нет.

**Comment by artbear** [comment]
@nixel2007 Расскажи, как повторить твою проблему?

**Comment by nixel2007** [comment]
Хм, странно. 
![image](https://cloud.githubusercontent.com/assets/1132840/21053799/1481dcbe-be3c-11e6-8830-92f75f031cb2.png)

Но при этом, если:
* взять gitrunner в ветке feature/test
* поменять, например, в фиче РаботаСВетками в сценарии "Переход на ветку" секцию Тогда на
`    Тогда Текущая ветка равна "develop1"`

То в консоли просто выводится
![image](https://cloud.githubusercontent.com/assets/1132840/21053846/44c947d6-be3c-11e6-83f9-2d72e7d5f5c9.png)

**Comment by EvilBeaver** [comment]
см. расследование: https://github.com/EvilBeaver/OneScript/pull/372#issuecomment-273891711

**Comment by EvilBeaver** [comment]
Закрываю?
