### ISSUE TITLE
Поправить текст ошибки установки

### ISSUE THREAD

**Issue by artbear** [oscript-library/opm#161]
Из телеграма

artkor, [15.04.19 15:01]
opm install "D:\gitsync-3.0.0-rc.2.ospx"
{Модуль C:\Program Files (x86)\OneScript\lib\opm\src\core\Классы\МенеджерПолученияПакетов.os / Ошибка в строке: 18 / Ошибка установки пакета D:\gitsync-3.0.0-rc.2.ospx: Пакет не найден}

artkor, [15.04.19 15:01]
хотя пакет там есть

Никита Грызлов, [15.04.19 15:02]
флаг -f забыли

artkor, [15.04.19 15:03]
все ок, спасибо

Игорь Сторожук, [15.04.19 15:48]
[In reply to artkor]
Тоже спотыкался на этом.
Наверное текст ошибки плохо сформулирован, не дает понять, что это не пакет по пути "D:\gitsync-3.0.0-rc.2.ospx", а такое имя пакета ищется
может так и написать "Ошибка установки пакета с именем "D:\gitsync-3.0.0-rc.2.ospx": Пакет не найден"
или сразу дописать возможно вы забыли флаг -f ?

**Comment by khorevaa** [comment]
Реализовано в рамках https://github.com/oscript-library/opm/pull/155
