### ISSUE TITLE
opm install --url

### ISSUE THREAD

**Issue by ghost** [oscript-library/opm#167]
Некоторые клиенты кто использует oscript - делают свои скрипты и публикуют их на Jenkins

Нужно подерживать возможность скачать и установить пакет с произвольного URL по аналогии с `opm install -f`

**Comment by asosnoviy** [comment]
#144

**Comment by EvilBeaver** [comment]
Тут наверное имелось в виду не с произвольного зеркала, а с артефактов дженкинса.

**Comment by asosnoviy** [comment]
Я имел ввиду что потребность, вроде как, закрывается частным хабом.

**Comment by allustin** [comment]
@asosnoviy зачем мне сущность в виде хаба  - в данном контексте именно Jenkins.

Вообще многие продукты сейчас позволяют устанавливать пакеты напрямую с github или с произвольного URL.

**Comment by asosnoviy** [comment]
Сделали?

**Comment by 240596448** [comment]
это можно закрыть
