### ISSUE TITLE
[BUG] Ошибка чтения параметров команды opm build

### ISSUE THREAD

**Issue by ovcharenko-di** [oscript-library/opm#172]
CWD: `C:\Users\dovcharenko\AppData\Local\Temp\r0m4acmf.dya.tmp`
Но воспроизводится в любой директории на моей машине.

Команда, которая отрабатывает с ошибкой:
opm build **-out** C:\Users\dovcharenko\AppData\Local\Temp\r0m4acmf.dya.tmp C:\repo\vanessa-runner

Вывод:
![image](https://user-images.githubusercontent.com/24920942/72619039-7a93e800-394d-11ea-9685-1b05b028b5aa.png)

Команда, которая отрабатывает корректно:
opm build **-o** C:\Users\dovcharenko\AppData\Local\Temp\r0m4acmf.dya.tmp C:\repo\vanessa-runner

**Comment by Stepa86** [comment]
Так 2 минуса у out должно быть

**Comment by ovcharenko-di** [comment]
точно же, не обратил внимания. однако, тесты в VA были именно с одним минусом.
