### ISSUE TITLE
При недоступности одного из зеркал установка пакета занимает значительно больше времени

### ISSUE THREAD

**Issue by nixel2007** [oscript-library/opm#184]
Кажется, надо подкрутить таймауты

**Comment by artbear** [comment]
Там вообще полная жесть.


любая команда тормозит, даже та, которая вроде как не должна ходить в интернет.

вопрос - зачем opm всегда ходит в интернет?

например, хелп по команде

![image](https://user-images.githubusercontent.com/2920817/96008199-fcb32d80-0e47-11eb-903b-670957755b47.png)

**Comment by EvilBeaver** [comment]
Хороший вопрос. Не знаю. Очевидно, что это так не должно быть

**Comment by GladilovDmitry** [comment]
В том числе при установке 1script через распаковку zip на изолированном от интернета машине получаем 8 сообщений об ошибке соединения с ОсновнойСерверПакетов и ЗапаснойСерверПакетов для команды просмотра локального списка пакетов opm list.

**Comment by artbear** [comment]
еще пример лога простейшей команды opm version при отключенном интернете
![image](https://user-images.githubusercontent.com/2920817/230012101-72e3fe2b-b346-4b77-ad0e-68b07478e9f2.png)

Повторю вопрос - зачем постоянно ходить в интернет??
