### ISSUE TITLE
opm install --all не использует штатный каталог LIB для установки

### ISSUE THREAD

**Issue by aliczin** [oscript-library/opm#191]
opm версия 1.0.2
Oscript - Stable и Dev

поведение одинаковое

![изображение](https://user-images.githubusercontent.com/56105699/97784158-8e8f9a00-1bad-11eb-85d1-0809748d775d.png)

проверить просто

```
ovm install stable
ovm use stable
opm install opm
opm install --all
```

![OpmInstallAll](https://user-images.githubusercontent.com/56105699/97784190-cb5b9100-1bad-11eb-8904-9b19c994a147.gif)

Ожидаемое поведение - все должно поставится в LIB

**Comment by nixel2007** [comment]
Ты используешь -all, а не --all, склеивая по правилам posix --all и --local

**Comment by aliczin** [comment]
@nixel2007 магия... а можно вообще убрать `-all` возможность ?

**Comment by aliczin** [comment]
Ладно буду знать и закрою

**Comment by nixel2007** [comment]
В команде можно проверить переданные флаги, но не знаю, можно ли узнать, было ли два -l. В любом случае, можно кинуть хотя бы ворнинг на -al комбинацию, потому что это и правда редкий кейс использования.

**Comment by aliczin** [comment]
@nixel2007 да ладно - ерунда в общем - ноги то растут вот откуда: я вообще хотел схитрить и для NetCore сделать скрипт

```
opm instal -all
#Иcпользовать ALL
```
чтобы в одном скрипте проверить компилируемость всей имеющихся библиотек - типа такой дымовой тест. Но там пока все на AST равзваилилось, так что данная задача - больше на будущий Pull-request.
