### ISSUE TITLE
[BUG] обновление пакетов удаляет плагины add

### ISSUE THREAD

**Issue by sulfur17** [oscript-library/opm#196]
Опишите ошибку
Выполняю команду "opm u -a" и все мои дополнительные плагины из папки add/plugins удаляются

Воспроизведение ошибки

В папку OneScript\lib\add\plugins\ добавляем любой файл
В cmd выполняем команду opm u -a
Увидеть что наш файл исчез
Ожидаемое поведение
Файлы должны остаться на месте

Окружение

ОС: Win10x64
Версия: 1.0.2

**Comment by artbear** [comment]
Как уже писали, Vanessa-add при установке очищает собственный каталог, это заложенное поведение. 

Собственные плагины следует располагать в отдельном каталоге, например, в репозитории вашего проекта или добавлять после обновления Ванесса-АДД
