### ISSUE TITLE
Доработать opm для Linux

### ISSUE THREAD

**Issue by artbear** [oscript-library/opm#2]
Хотелось бы на линукс повторить "удачное" поведение opm из Windows

Автор @artbear 

> Цель/требование - после `opm install МойПакет` или `opm app МойПакет` я мог сразу вызывать `МойПакет` без дополнительных телодвижений!

Автор @nixel2007 

> ```
> Когда МойПакет содержит в описании ИсполняемыйФайл test
> Тогда после выполнения opm install МойПакет из командной строки доступна команда test
> ```
> 
> оно так работает на винде, но не работает на линуксе. значит цель - заставить его так работать на линуксе

Автор @dmpas 

> делаю `sudo apt purge onescript` и в системе не остаётся ни одного файла, так или иначе установленного посредством этих ваших `opm`, за исключением того, что лежит в домашних каталогах.

**Comment by nixel2007** [comment]
Нашел в истории коммитов https://github.com/oscript-library/opm/commit/45fd342692161b7d8ef10dcbfd4849e4730ca6ed от @dmpas 
Т.е. скрипт уже как бы даже есть... Нужно его просто положить в правильный bin?

**Comment by artbear** [comment]
Да, я также проверял код opm для Линукс.
Файл формируется верный, его именно нужно положить в правильное место.

**Comment by dmpas** [comment]
Ознакомился с "братьями старшими" (npm, pip) - все гадят символическими ссылками в `/usr/bin`. После удаления пакетного менеджера всё это борохло остаётся лежать там и даже работоспособно, по большому счёту.

Учитывая, что "единственно правильного" решения мы всё равно не нашли, предлагаю делать, как все:

исполняемый shell-скрипт лежит в `/usr/share/oscript/lib/MYAPP/где-то-тут`, в `/usr/bin` на него лежит символическая ссылка.
