### ISSUE TITLE
Не используется зеркало hub.oscript.ru

### ISSUE THREAD

**Issue by dmpas** [oscript-library/opm#202]
То ли opm сломался, то ли с хабом чего

**Comment by nixel2007** [comment]
разве list.txt еще обновляется хабом? я думал, там все переведено на бэкэнд с entity

**Comment by dmpas** [comment]
как минимум opm работает через list.txt
и да, list.txt обновляется хабом.

**Comment by EvilBeaver** [comment]
Теперь надо пересобрать получается движок освеба и накатить на хост?

**Comment by dmpas** [comment]
@EvilBeaver ага
