### ISSUE TITLE
Реестр пакетов GitFlic. Добавить авторизационный токен

### ISSUE THREAD

**Issue by kirillfb** [oscript-library/opm#216]
Нужна возможность от клиента прокидывать токен (произвольную строку) в запрос для идентификации пользователя, чтобы, например, давать возможность скачивания пакета из приватного ресурса

Для команды push добавляется заголовок OUATH-TOKEN, подобный вариант на GET запросы, уходящие с командами с командами install/update/list подойдет

**Comment by EvilBeaver** [comment]
Лучше, наверное, стандартный Authentication: Bearer

**Comment by dmpas** [comment]
с учётом того, что install/update/list ломится по списку зеркал, то посылать в каждое зеркало один и тот же токен из командной строки малость небезопасно.
Если мы предполагаем, что у нас opm работает по своему списку частных серверов, то и токен стоит прописывать в opm.cfg.
Или сам токен, или имя переменной с токеном. Или вообще произвольные добавляемые заголовки.

**Comment by nixel2007** [comment]
Или токен или имя переменной среды звучит прям по-мавеновски, мне нравится

**Comment by EvilBeaver** [comment]
Ну да, однозначно токены надо хранить в разрезе серверов. И нет, Никита, мы не будем делать xml-конфиг, как в мавене, у нас и так от явы ОСень и ентити просочились.

**Comment by nixel2007** [comment]
Зачем xml, у opm уже есть свой конфиг

**Comment by EvilBeaver** [comment]
> Зачем xml, у opm уже есть свой конфиг

Да я троллю. Услышал мавен и тригернулся. Фиксируем:

В конфиге opm нужно хранить токены в разрезе серверов-зеркал.
