### ISSUE TITLE
bat, создаваемый `opm app` нельзя вызвать из git bash под виндой

### ISSUE THREAD

**Issue by nixel2007** [oscript-library/opm#23]
Сабж.
Очень напрягает.

**Comment by nixel2007** [comment]
Точнее можно, но
* требуется указание расширения .bat
* кривая кодировка в консоли

**Comment by EvilBeaver** [comment]
а в гитбаше вообще баты можно вызывать?

**Comment by nixel2007** [comment]
@EvilBeaver хз, вроде нет. но я больше к тому, что может мы под виндой тоже будем собирать sh-файлик? и класть его туда же в onescript/bin
