### ISSUE TITLE
Хранение метаинформации об установленном пакете

### ISSUE THREAD

**Issue by nixel2007** [oscript-library/opm#24]
При установки из ospx/opm дополнительно класть в корень библиотеки packagedef или какой-то другой файл информации (предпочтительно json)

P.S. у packagedef есть проблема с обратной совместимостью - новый packagedef нельзя прочитать старым opm, т.к. будут ошибки вызова несуществующих процедур (например недавно добавленное Задачи() )

**Comment by EvilBeaver** [comment]
Проблему обратной совместимости я бы сейчас не рассматривал.

**Comment by artbear** [comment]
>Проблему обратной совместимости я бы сейчас не рассматривал.

+1
