### ISSUE TITLE
Зеркала

### ISSUE THREAD

**Issue by dmpas** [oscript-library/opm#25]
25 декабря 2016г:
```
>opm list -remote
Внешнее исключение (System.Net.WebException): Невозможно соединиться с удаленным сервером
```

Предлагаю:
1. создать зеркало хаба:
   * зеркало должно уметь обновляться с основного узла
   * зеркало не должно ничем отличаться по структуре от основного узла (за исключением адреса сайта и корневого пути)
2. научить opm, что пакеты можно качать не только с одного места

**Comment by artbear** [comment]
+1

**Comment by artbear** [comment]
А кандидаты на зеркала есть?

**Comment by dmpas** [comment]
У меня два хостинга на постоянке есть.
На крайний случай есть всякие bintray.

**Comment by EvilBeaver** [comment]
Пока болел, продолбал продление VDS. Теперь все работает. Задачу поддерживаю.

**Comment by dmpas** [comment]
https://hub.oscript.ru/

Отзеркалил хаб. Синхронизация раз в сутки. Теперь надо opm допиливать.

**Comment by nixel2007** [comment]
Просто отмечу, что на андроиде в хроме ругается на сертификат

**Comment by dmpas** [comment]
@nixel2007 моно под убунтой вообще в отказ идёт :) задача известна, мы ещё в самом начале пути....
