### ISSUE TITLE
Добавить dev-зависимости

### ISSUE THREAD

**Issue by artbear** [oscript-library/opm#26]
@nixel2007 Для обсуждения

**Comment by dmpas** [comment]
@artbear можешь подробнее разъяснить?

**Comment by nixel2007** [comment]
в ноде есть два типа зависимостей
обычные зависимости ставятся при установке из хаба пакетов.
дев-зависимости ставятся только при установке из хаба пакетов со специальным флагом (это не так важно) или при выполнении `npm install` в каталоге пакета (например, гит репозиторий) - вот это уже важно.

**Comment by nixel2007** [comment]
т.е. если я качаю гитраннер с опм мне не нужны `1bdd` и `asserts`. а если я открываю репо гитраннера и выполняю opm install - нужны, т.к. это явно установка для полноценной работы и разработки.

**Comment by dmpas** [comment]
для начала для тупых ненавистников npm и javascript-а, "dev-зависимость" - это зависимость, нужная для разработки текущего пакета, или зависимость текущего пакета от другого пакета версии, находящейся в состоянии разработки, не выпущенной?

**Comment by nixel2007** [comment]
"dev-зависимость" - это зависимость, нужная для разработки текущего пакета

**Comment by nixel2007** [comment]
для прогона тестов, например. тестовые фреймворки не помогают в "обычной" работе.

**Comment by EvilBeaver** [comment]
@nixel2007 а чем дев-зависимости отличаются от обычных? Мы разрабатываем пакет и ставим просто зависимости. Судя по ответам выше - dev-зависимости это не какие-то "сырые" пакеты, верно? Тогда чем они отличаются?

**Comment by nixel2007** [comment]
дев-зависимости пакета, который ты ставишь через `opm install ИмяПакета` (т.е. из хаба), не установятся в систему.

**Comment by EvilBeaver** [comment]
Чо?

**Comment by nixel2007** [comment]
Ещё разок. 
Есть у меня гит раннер. У него в зависимостях есть strings и 1bdd.
1bdd нужен только разработчику самого гитраннера, чтобы прогонять тесты. Strings нужен пользователю гитраннера, так как без strings не будет работать сам гитраннер как таковой. 

Вот такие ситуации разруливаются дев-зависимостями. 1бдд добавляется в дев-зависимости и он *не* скачивается при установке гитраннера из хаба. А стринггс - скачивается

**Comment by EvilBeaver** [comment]
а нахрена вообще дев зависимости, если их не скачивать?

**Comment by dmpas** [comment]
@EvilBeaver их скачивает разработчик для разработки. после того, как пакет собран и ушёл в хаб, конечному пользователю эта зависимость не нужна совсем.

**Comment by nixel2007** [comment]
@EvilBeaver угу, @dmpas дело говорит.

если ты - разработчик, ты в каталоге проекта выполняешь opm install без параметров и у тебя ставятся все зависимости, в том числе dev.

**Comment by Khorevaa** [comment]
Поддерживаю. Очень не хватает данного функционала.  Вот теперь после доработк opm ( по [PR](https://github.com/oscript-library/opm/pull/40)) он должен требовать dev зависимость 1testrunner 1.4
