### ISSUE TITLE
opm build && opm install -f

### ISSUE THREAD

**Issue by dmpas** [oscript-library/opm#4]
делаю `opm build .`, мне честно собирается файл с именем `InternetMail-1.0.0.ospx`.

делаю `opm install -f InternetMail-1.0.0.ospx` и вот же ж незадача: в каталоге lib создаётся каталог `InternetMail-1.0.0` (с версией). И я не могу подключать библиотеку простым `#use InternetMail`.

Приходится лезть в либы и переименовывать каталог.

Вопрос: как избежать всего этого геморроя?

**Comment by EvilBeaver** [comment]
Запилить адекватный код в opm. Или там уже есть то-ли ключи ком.строки для build то ли код внутри....

**Comment by dmpas** [comment]
Отбой. В свежем opm уже всё чётко.
