### ISSUE TITLE
При установке пакета не очищается каталог.

### ISSUE THREAD

**Issue by asosnoviy** [oscript-library/opm#41]
[Исходная проблема](https://github.com/oscript-library/gitsync/issues/27)
В прошлой версии gitsync был файл класса, потом класс уехал в отдельную библиотеку.
При  opm gitsync update ставится новая версия. Старый Файл не удаляется.

**Comment by asosnoviy** [comment]
Предложение чистить src пакета если он уже был установлен.  
P.S. Конфигу opm наверно не место в src...

**Comment by asosnoviy** [comment]
Еще варианты:  
1. PostInstall скрипт в пакете. 
2. Список файлов пакета.
2. Список файлов которые не надо удалять из src.

**Comment by nixel2007** [comment]
Взято в работу.
