### ISSUE TITLE
Сделать регистронезависимым установщик пакетов opm install

### ISSUE THREAD

**Issue by xzorkiix** [oscript-library/opm#50]
Ошибка
```
C:\Users\ShabalinE>opm install precommit1C
ИНФОРМАЦИЯ - Скачиваю файл: precommit1C.ospx
Ошибка установки пакета precommit1C <404>
```

Правильно
```
C:\Users\ShabalinE>opm install precommit1c
ИНФОРМАЦИЯ - Скачиваю файл: precommit1c.ospx
ИНФОРМАЦИЯ - Устанавливаю пакет precommit1c
ИНФОРМАЦИЯ - Устанавливаю зависимость: logos
ИНФОРМАЦИЯ - Устанавливаю зависимость: cmdline
ИНФОРМАЦИЯ - Устанавливаю зависимость: tempfiles
ИНФОРМАЦИЯ - Устанавливаю зависимость: asserts
ИНФОРМАЦИЯ - Устанавливаю зависимость: v8runner
ИНФОРМАЦИЯ - Устанавливаю зависимость: strings
ИНФОРМАЦИЯ - Регистрация приложения: precommit1c
ИНФОРМАЦИЯ - Установка завершена
```

**Comment by xzorkiix** [comment]
Добавлю что регистрозависимость начинается с http://hub.oscript.io/download/

http://hub.oscript.io/download/precommit1C/ -- 404

http://hub.oscript.io/download/precommit1c/ -- 200

**Comment by EvilBeaver** [comment]
Против. Во-первых, зачем писать в командной строке в неправильном регистре. Во-вторых, в линуксе командная строка регистрозависимая и все понимают, что это хорошо.

**Comment by asosnoviy** [comment]
В пользу регистронезависимых имен пакетов
InternetMail  
ParserFileV8i

**Comment by nixel2007** [comment]
Я вот скорее за. Особенно после ParserFileV8i

**Comment by dmpas** [comment]
> Во-вторых, в линуксе командная строка регистрозависимая

не совсем так. Регистрозависимость - это не фишка линукса, а настройка файловой системы.

второе: имя файла и имя пакета - разные сущности. Имя файла привязано к особенностям файловой системы и все это понимают. Имя пакета, на мой взгляд, должно отвечать задачам и потребностям самой экосистемы движка.

**Comment by EvilBeaver** [comment]
Ну собсна ппкеты хостятся на линуксе, отсюда и регистрозависимость. Как ее решить в случае v8parser не знаю. Может затребовать, чтобы все файлы пакетов именовались мелкими буквами?

**Comment by dmpas** [comment]
Всё проще. Есть list.txt, в котором лежат названия в нужном регистре. Его можно скачивать и делать соответствие.

**Comment by nixel2007** [comment]
Разве в случае веб-сервиса это не одна строчка где-нибудь в htaccess или конфе самого сервера?

**Comment by artbear** [comment]
Я за регистронезависимость.
