### ISSUE TITLE
При установке пакетов более новых версии не происходит очищение каталога установки

### ISSUE THREAD

**Issue by Khorevaa** [oscript-library/opm#56]
Для теста. Установить новую версию gitsync. Перестанет работатьиз-за наличия лишнего файла "КомандыйФайл.os"

**Comment by nixel2007** [comment]
Это было исправлено в одной из последних версий opm

**Comment by Khorevaa** [comment]
Как раз в последней и не работает...

**Comment by nixel2007** [comment]
Давай еще раз.
opm install opm
opm install gitsync

После этого в папке гитсинка не должно остаться лишних os файлов

**Comment by Khorevaa** [comment]
Пробовал

**Comment by artbear** [comment]
Да, такой баг исправляли.
Напиши результат команды `opm list`

**Comment by Khorevaa** [comment]
```
Пакеты в системном каталоге библиотек </usr/share/oscript/lib>:
1bdd@1.3
1commands@1.1
1testrunner@1.4.3
asserts@0.3.1
cmdline@0.4.1
fs@0.3
gitrunner@1.0.0
gitsync@2.1
json@0.2.1
logos@0.5
opm@0.9.3
strings@0.4.1
tempfiles@0.2.1
tool1cd@0.3
v8runner@0.7.1

```

**Comment by nixel2007** [comment]
> /usr/share/oscript/lib

на линуксах не тестировали.
Вообще код вот - https://github.com/oscript-library/opm/blob/master/src/%D0%9A%D0%BB%D0%B0%D1%81%D1%81%D1%8B/%D0%A3%D1%81%D1%82%D0%B0%D0%BD%D0%BE%D0%B2%D0%BA%D0%B0%D0%9F%D0%B0%D0%BA%D0%B5%D1%82%D0%B0.os#L323

**Comment by artbear** [comment]
для линукса поведение, кстати, не проверяли :)

**Comment by Khorevaa** [comment]
Хм.. проверил пару раз в принципе почищает не понятно почему с  первой попытки не почистил..
