### ISSUE TITLE
opm install -all падает при первом использовании

### ISSUE THREAD

**Issue by artbear** [oscript-library/opm#58]
opm update opm и далее opm install -all падает неожиданно при первом использовании
Например, на чистой машине поставили 1скрипт и пытаемся обновить библиотеки

ругается на Свойство объекта не обнаружено (СоздаватьSHСкриптЗапуска

**Comment by nixel2007** [comment]
Машина не похожа на чистую. Такая ошибка возникает только если настроить конфиг опм, а потом обновить опм. Ты скорее всего настраивал прокси

**Comment by artbear** [comment]
@nixel2007 Шаман, однако.
А я пробовал настраивать на чистой машине разные варианты, не смог повторить.
А у клиента как раз был прокси.

**Comment by artbear** [comment]
@nixel2007 Может быть, ты уже знаешь, как и где поправить для исключения ошибки?

**Comment by nixel2007** [comment]
@artbear добавить этот ключ в opm.config (json)  в папке установки опм/src

**Comment by nixel2007** [comment]
А если ты про код - то нужно обработать отсутствие ключей в объекте при чтении конфига.

**Comment by artbear** [comment]
Сделаю вечером, с фичами :)

**Comment by artbear** [comment]
Ошибка исправлена. Добавлена первая фича проекта и ее реализация
