### ISSUE TITLE
Стабильный канал пакетов

### ISSUE THREAD

**Issue by dmpas** [oscript-library/opm#60]
Предлагаю разделить хаб на стабильный канал и канал разработки.
1. весь самый свежак сначала кладётся на dev-канал (alpha-канал, как угодно), его качают те, кому это дико нужно, пользуются, ругаются, чинят
2. спустя какое-то время использования видим, что ошибки не валятся, добавляем пакет в стабильный канал и он расходится простым пользователям.
3. соответственно всему этому в настройки opm надо добавить настройку, ЯВНО указывающую, что пользователь в здравом рассудке и трезвой памяти будет качать нестабильные обновления с dev-канала.

**Comment by artbear** [comment]
Здравое предложение, проголосовал за

**Comment by nixel2007** [comment]
Кто будет решать о переводе релиза в стейбл? 
У @asosnoviy была идея просто добавить nightly-сборки. И ставить их при желании через opm install v8runner@nightly

**Comment by nixel2007** [comment]
Вообще прохождение тестов в мастер ветке изначально показатель стабильности :(

Я понимаю, что у нас внезапно возник сразу ряд проблем в нескольких пакетах, но морозить из-за этого всю разработку как-то не хочется.

**Comment by dmpas** [comment]
@nixel2007 хотели же каждому пакету ответственного назначить. неделю-две нет сообщений об ошибках - кидаем в стабильную.

морозить разработку и не надо. морозить надо желание поделиться с миром свежеиспечёнными косяками. девелопу как девелопили, так и будем девелопить.

**Comment by dmpas** [comment]
nightly вообще тоже вполне себе выход. проще, но хуже.

**Comment by artbear** [comment]
Я против явного выделения ответственных, это будет сильно тормозить процесс :(
у нас есть знающие люди, которые по возможности выпускают, мержат, принимают PR, и это прекрасно работает.
