### ISSUE TITLE
Непонятная ошибка 404 при установке пакета

### ISSUE THREAD

**Issue by nixel2007** [oscript-library/opm#63]
`opm install strange` ругается с 404-ой ошибкой, что не совсем понятно для пользователя.
Вероятнее всего, раз мы получили 404, значит пользователь либо пытается скачать несуществующий пакет либо лежат все зеркала сразу. Нужно пользователю сказать об этом явно.

**Comment by EvilBeaver** [comment]
Если лежат все зеркала сразу то код ошибки будет другой. 404 ясно и понятно на мой взгляд

**Comment by EvilBeaver** [comment]
Гитхаб не закрыл автоматом. Делаю за него.
