### ISSUE TITLE
opm 1.0

### ISSUE THREAD

**Issue by dmpas** [oscript-library/opm#64]
Что мешает сделать наконец-то 1.0 ???

@nixel2007 @EvilBeaver

**Comment by nixel2007** [comment]
Не все core-фичи еще доделаны :)
Нормальная работа с ремоутом, oscript-modules, проверка на необходимость обновления opm.
За 0.9 вполне может следовать 0.10. :)

**Comment by dmpas** [comment]
я понимаю, что за 0.9 следует 0.10, я не понимаю, почему вещь, которой все пользуются из коробки, до сих пор в бете сидит.

эта штука хорошо умеет скачивать и обновлять - этого достаточно в подавляющем большинстве случаев.

**Comment by nixel2007** [comment]
Не хочу делать breaking change после 1.0
Например, хорошо бы перевести все ключи в единый формат с короткими/длинными именами. Значит, появятся депрейкейтед ключи.
Из разряда "не красиво" :)
В целом-то да, инструмент есть и работает.

**Comment by dmpas** [comment]
за breaking change шишки в тебя полетят независимо от того, 0.9999 у тебя или 1.0. Всё равно будут депрекейтеды.

**Comment by nixel2007** [comment]
На 0.х можно прикрываться семвером и "а чо вы от беты хотели?" :D

**Comment by dmpas** [comment]
так мы и на 1.х прикрываемся опенсурсом и отказом от ответственности.

**Comment by EvilBeaver** [comment]
Мое имхо. Делаем локальные установки модулей и вперед, в 1.0

С другой стороны, многие пооекты годами живут с ноликом в начале, а все пользуются

**Comment by artbear** [comment]
Локальные установки заработали же, верно?
может быть, уже пора 1.0 ?

**Comment by dmpas** [comment]
Подниму вопрос.

**Comment by EvilBeaver** [comment]
Надо еще подход сделать к ней. И настройки перепилить, а то сейчас настройки прокси убого задаются

**Comment by nixel2007** [comment]
self-contained opm надо доделать

**Comment by dmpas** [comment]
Подниму вопрос.

**Comment by EvilBeaver** [comment]
Лучший способ - сменить формат манифеста

**Comment by nixel2007** [comment]
@EvilBeaver ничоси. за это надо ~выпить~ обсудить.

**Comment by EvilBeaver** [comment]
Я те вчера звонил, но ты пропал, как обычно.

Имеем: 

* Руби и Питон используют "кодовые" манифесты, как и опм. Как они с ними живут и какой там workflow разработки с использованием сторонних пакетов?
* NPM использует json манифест. workflow известен - install --save и прочее. Как в JS прописывают скриптовые части манифеста, сборку, установку, удаление?

**Comment by nixel2007** [comment]
Перекладывая волшебные названия скриптов на рельсы опм, получаются волшебные названия тасков в каталоге тасков. Один волшебный таск у нас уже есть - это test. Он вызывается по короткому алиасу opm test, хотя может вызываться по полному имени как opm run test

**Comment by khorevaa** [comment]
Давайте все же манифест в формате json... по аналогии с npm.....
Сейчас из-за этого не возможно скопилить приложение opm в exe

**Comment by nixel2007** [comment]
Опм не компилируется ехе, потому что там используется загрузитьсценарий в манифесте. Если его убрать, то должен компилироваться. Так что формат пэкэдждефа тут не первопричина

**Comment by dmpas** [comment]
нам нужен 1SON (на правах трололо)

**Comment by EvilBeaver** [comment]
в формате 1SON (1S object notation) у как раз и есть сейчас. Лучшая нотация - никаких нотаций. Только динамически наполняемый объект )

**Comment by khorevaa** [comment]
@nixel2007 Не только из-за ЗагрузитьСценарий в packagedef еще из-за того что сам packagedef тоже загружается через ЗагрузитьСценарий. А в exe данной функции нет.

**Comment by nixel2007** [comment]
@khorevaa поясни, пожалуйста.

1. opm читает свой собственный packagedef? Зачем?
2. Прям вот совсем такой функции нет? Я думал проблемы только в (обычно) неверных путях, которые передают этой функции. т.к. они начинают шагать непонятно откуда и относительные каталоги ведут непонятно куда

**Comment by khorevaa** [comment]
@nixel2007 
1. Вроде не читал!
2. Функция в exe есть! Проблема только в относительных путях!


Хотя я все же за смену формата на json/yaml/toml/ini! -:) Столько всего можно реализовать!

**Comment by EvilBeaver** [comment]
Ок, давайте введем новый формат описания packagedef. Допустим, сначала обрабатывается новый файл, а затем старый (или еще как)

**Comment by artbear** [comment]
уже 1.2.2 - закрываю тикет
