### ISSUE TITLE
Исключать каталоги не библиотек из процедуры обновления

### ISSUE THREAD

**Issue by JohnyDeath** [oscript-library/opm#71]
```
opm update -all
КРИТИЧНАЯОШИБКА - {Модуль ...\OneScript\lib\opm\src\Классы\УстановкаПакета.os / Ошибка в строке: 263 / Ошибка установки пакета .vscode: Пакет не найден}
```
".vscode" - каталог хранения настроек редактора VSC
Предлагаю убрать из анализа все каталоги, начинающиеся с "."
А вообще, наверное, лучше смотреть на наличие файла packagedef в каталоге
Как считаете?

**Comment by nixel2007** [comment]
> на наличие файла packagedef в каталоге

этого файла не должно быть в каталоге :) после какого-то релиза обязательно валяется opm-metadata.xml, можно к нему привязаться.

**Comment by JohnyDeath** [comment]
не успеваю за вами )

**Comment by EvilBeaver** [comment]
@JohnyDeath с днем рождения! И я тоже за ними перестаю успевать (

**Comment by JohnyDeath** [comment]
@nixel2007 можешь пояснить вот этот кусок: https://github.com/oscript-library/opm/blob/master/src/Классы/КэшУстановленныхПакетов.os#L100-L102
Это на период, пока не все локальные пакеты перешли на новый-модный opm-metadata.xml ?

Правильно ли будет посмотреть в этом "иначе" наличие файла "packagedef" и при его отсутствии сразу делать возврат без добавления в УстановленныеПакеты ?

**Comment by nixel2007** [comment]
> Это на период, пока не все локальные пакеты перешли на новый-модный opm-metadata.xml ?

Почти - пока не обновили opm и не выполнили апдейт, думаю, ближе к концу года (или к 1.0) можно будет дропнуть. 

> Правильно ли будет посмотреть в этом "иначе" наличие файла "packagedef" и при его отсутствии сразу делать возврат без добавления в УстановленныеПакеты ?

Смотря чего ты хочешь добиться. Не обновлять не-пакеты? Тогда, наверное, да, можно временно это анализировать (до 1.0 опять же). Только нужно выполнить чистую установку движка, например, 1.0.15 и проверить, что во всей стандартной библиотеке есть packagedef

**Comment by JohnyDeath** [comment]
Как-то страшно всё )
Пожалуй лучше будет дождаться-таки 1.0 и дропать. А если у кого-то возникнуть разовые проблемы с обновлением непакетов, то их можно решить точечно.
Закрою задачу.
