### ISSUE TITLE
Падение на получении данных о зеркалах при включенном прокси по умолчанию

### ISSUE THREAD

**Issue by nixel2007** [oscript-library/opm#73]
```
C:\Users\na_gryzlov>opm update opm
WARNING! Deprecated method: 'SystemInfo.GetEnvironmentVariable' is deprecated, use 'GetEnvironmentVariable' from global context
КРИТИЧНАЯОШИБКА - {Модуль C:\Program Files (x86)\OneScript\lib\opm\src\Классы\Зеркало.os / Ошибка в строке: 16 / Преобразование к типу 'Число' не поддерживается}
```

**Comment by best-tech** [comment]
подтверждаю
opm  update -all
WARNING! Deprecated method: 'SystemInfo.GetEnvironmentVariable' is deprecated, use 'GetEnvironmentVariable' from global context
КРИТИЧНАЯОШИБКА - {Модуль C:\Program Files (x86)\OneScript\lib\opm\src\Классы\Зеркало.os / Ошибка в строке: 16 / Преобразование к типу 'Число' не поддерживается}

**Comment by artbear** [comment]
Исправлено.
