### ISSUE TITLE
opm push должен писать в консоль об успешной отправке файла на хаб

### ISSUE THREAD

**Issue by artbear** [oscript-library/opm#85]
`opm push` отработал, в дев-канале вижу свежую дату и время
одно но:
```cmd
C:\projects\params>opm push --file params-0.3.ospx --channel dev --token ХХХ
ИНФОРМАЦИЯ -
```
никакой инфы об успешности не пишется :(

Предлагаю добавить сообщения 
```
Файл params-0.3.ospx выгружен в dev-хаб по адресу http://hub.oscript.io/dev-channel/params
```

**Comment by nixel2007** [comment]
Это не в этот репо. весь сервер-сайд в oscript-infrastructure

**Comment by artbear** [comment]
Закрываю.
т.к. команда пуш выдает ошибку, если не удалось отправить.
т.е - если нет никаких ошибок, считаем, что файл отправлен
