### ISSUE TITLE
Обновить logos в поставке и выпустить релиз для исключения багов в 19/20 релизе

### ISSUE THREAD

**Issue by artbear** [oscript-library/opm#93]
@nixel2007:
+ @artbear бампнуть пэкэдждеф на новую версию logos и пересобрать.
+ Ну и выложить.
  + Через обычный opm install opm должно обновиться.
+ На всякий случай в класс установщика, который чистит все os и dll в папке можно добавить удаление каталога оскрипт_модулес
+ добавь заодно пропущенную зависимость от 1коммандс, если это не сделано.

**Comment by nixel2007** [comment]
это не баги 19/20 релиза. это баг логоса :)
добавь заодно пропущенную зависимость от 1коммандс.

**Comment by artbear** [comment]
я тупо поставил релиз, и существующий у меня код упал, хотя ранее работал.

я говорю с точки зрения пользователя.

вчера вечерком решил на АДД перед Шерлоком поработать часа полтора.
и нифига, все падает, валится и т.п.
пришлось баги исправлять после обычной установки релиза :)

**Comment by nixel2007** [comment]
все больше склоняюсь к Андрюхиному мнению убрать нахрен все библиотеки из stdlib.

**Comment by artbear** [comment]
>добавь заодно пропущенную зависимость от 1коммандс.

я смотрю исходники opm, там нет зависимости от 1коммандс :(
@nixel2007 подскажи

**Comment by nixel2007** [comment]
@artbear и вправду. значит в гитраннере надо. сделаю сейчас.

**Comment by artbear** [comment]
в гитраннере зависимость есть, все хорошо. 
ИМХается мне, что я ее исправлял как раз после выпуска релиза движка

**Comment by nixel2007** [comment]
а, ну значит, надо в опм бампнуть зависимость от гитраннера. там сейчас 1.5.0 стоит

**Comment by artbear** [comment]
Выполнено

**Comment by artbear** [comment]
>а, ну значит, надо в опм бампнуть зависимость от гитраннера. там сейчас 1.5.0 стоит

упс, не увидел, а релиз не выпустил :)

**Comment by artbear** [comment]
Установить номер версии на 1.0.0

**Comment by nixel2007** [comment]
про ВерсияOPM не забудь

**Comment by EvilBeaver** [comment]
Закрыть?
